### PR TITLE
More fixes for Windows

### PR DESCRIPTION
**Pull request by cwenger**

### CODE REVIEW

**Comment by sa501428** [comment]
Hey @cwenger! Could you actually implement the shorts/ints/longs with stdint.h as in @nchernia's suggestion?  https://github.com/aidenlab/straw/pull/69#pullrequestreview-670540582
Also for reference: https://github.com/aidenlab/straw/pull/69#issuecomment-850593502

**Comment by cwenger** [comment]
@sa501428 Sure I'll give it a try!

**Comment by cwenger** [comment]
Ok @sa501428 see what you think. I wasn't sure if I should use the fixed size integers everywhere or only for data read from .hic files and I ended up somewhere in between.

**Comment by cwenger** [comment]
@sa501428 Just seeing if you've had an opportunity to take a look at these changes yet. Thanks!

**Pull request merged**
